version: '3'
services:
  app:
    build: .
    ports:
      - '8080:80'
    volumes:
      - ./html:/var/www/html

  appdb:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=app
      - MYSQL_DATABASE=app