version: '3.7'
services:
  app:
    build: .
    ports:
      - '8080:80'
    volumes:
      - ./html:/var/www/html
    env_file:
      - .env
  appdb:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}